### PR TITLE
Webpack inspired license proposal

### PR DESCRIPTION
**Pull request by WyriHaximus**
As discussed here is a proposal based on the webpack license for branding

### CODE REVIEW

**Review by jsor — APPROVED** [review]

**Review by clue — APPROVED** [review]
Should add a note that this is inspired by webpack license, otherwise LGTM :+1:

**Comment by WyriHaximus** [comment]
> Should add a note that this is inspired by webpack license, otherwise LGTM 👍

At the bottom of the license file? Like this:
```
This license is inspired by the webpack media license: https://github.com/webpack/media/blob/master/LICENSE
```

**Comment by jsor** [comment]
In the credits section maybe?

**Review by cboden — APPROVED** [review]

**Comment by WyriHaximus** [comment]
> In the credits section maybe?

Done

**Review by clue — APPROVED** [review]

**Review by jsor — APPROVED** [review]

**Pull request merged**
